version: '3.8'
services:
  back:
    build:
      context: ..
      dockerfile: docker/back.dockerfile
    container_name: exchange-back
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGO_URI
      - PG_HOST
      - PG_DB
      - PG_USER
      - PG_PASSWORD
      - PG_TABLE

    depends_on: []
    restart: unless-stopped

  front:
    build:
      context: ..
      dockerfile: docker/front.dockerfile
    container_name: exchange-front
    ports:
      - "8004:80"
    depends_on:
      - back
    restart: unless-stopped
